//
//  ListPhotoInteractor.swift
//  MarsRovers
//
//  Created by Henrique Velloso on 06/03/19.
//  Copyright (c) 2019 Henrique Velloso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPhotoBusinessLogic
{
  func doSomething(request: ListPhoto.Something.Request)
}

protocol ListPhotoDataStore
{
  //var name: String { get set }
}

class ListPhotoInteractor: ListPhotoBusinessLogic, ListPhotoDataStore
{
  var presenter: ListPhotoPresentationLogic?
  var worker: ListPhotoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListPhoto.Something.Request)
  {
    worker = ListPhotoWorker()
    worker?.doSomeWork()
    
    let response = ListPhoto.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
