//
//  ListPhotoPresenter.swift
//  MarsRovers
//
//  Created by Henrique Velloso on 06/03/19.
//  Copyright (c) 2019 Henrique Velloso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPhotoPresentationLogic
{
  func presentInitialData(response: ListPhoto.Load.Response)
}

class ListPhotoPresenter: ListPhotoPresentationLogic
{
  weak var viewController: ListPhotoDisplayLogic?
  
  // MARK: Do something
  
  func presentInitialData(response: ListPhoto.Load.Response)
  {
    let viewModel = ListPhoto.Load.ViewModel(photos: response.photos)
    viewController?.displayInitialData(viewModel: viewModel)
    
  }
}
