//
//  ListPhotoInteractor.swift
//  MarsRovers
//
//  Created by Henrique Velloso on 06/03/19.
//  Copyright (c) 2019 Henrique Velloso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPhotoBusinessLogic
{
    func doLoadInitialData(request: ListPhoto.Load.Request)
    func doLoadPhotoDetail(request: ListPhoto.Detail.Request)
}

protocol ListPhotoDataStore
{
    var photo: Photo? { get set }
}

class ListPhotoInteractor: ListPhotoBusinessLogic, ListPhotoDataStore
{
    var photo: Photo?

    var presenter: ListPhotoPresentationLogic?
    var worker: ListPhotoWorker?
    var photos: [Photo] = []
    
    // MARK: Do something
    
    func doLoadInitialData(request: ListPhoto.Load.Request)
    {
        worker = ListPhotoWorker()
        worker?.fetchPhotos(roverName: request.rover, earthDate: request.earthDate, completionHandler: { photos in
            self.photos = photos
            let response = ListPhoto.Load.Response(photos: photos)
            self.presenter?.presentInitialData(response: response)
            
        })
        
        
    }
    
    func doLoadPhotoDetail(request: ListPhoto.Detail.Request) {
        photo = request.photo
        let response = ListPhoto.Detail.Response()
        presenter?.presentPhotoDetail(response: response)
        
    }
}
