//
//  ListPhotoRouter.swift
//  MarsRovers
//
//  Created by Henrique Velloso on 06/03/19.
//  Copyright (c) 2019 Henrique Velloso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListPhotoRoutingLogic
{
  func routeToPhotoDetail(segue: UIStoryboardSegue?)
}

protocol ListPhotoDataPassing
{
  var dataStore: ListPhotoDataStore? { get }
}

class ListPhotoRouter: NSObject, ListPhotoRoutingLogic, ListPhotoDataPassing
{

    
  weak var viewController: ListPhotoViewController?
  var dataStore: ListPhotoDataStore?
  
  // MARK: Routing
  
  func routeToPhotoDetail(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ShowPhotoViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowPhotoViewController") as! ShowPhotoViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: ListPhotoViewController, destination: ShowPhotoViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: ListPhotoDataStore, destination: inout ShowPhotoDataStore)
  {
    destination.photo = source.photo
  }
}
