//
//  ShowPhotoInteractor.swift
//  MarsRovers
//
//  Created by Henrique Velloso on 06/03/19.
//  Copyright (c) 2019 Henrique Velloso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowPhotoBusinessLogic
{
  func doSomething(request: ShowPhoto.Something.Request)
}

protocol ShowPhotoDataStore
{
  //var name: String { get set }
}

class ShowPhotoInteractor: ShowPhotoBusinessLogic, ShowPhotoDataStore
{
  var presenter: ShowPhotoPresentationLogic?
  var worker: ShowPhotoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowPhoto.Something.Request)
  {
    worker = ShowPhotoWorker()
    worker?.doSomeWork()
    
    let response = ShowPhoto.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
