//
//  ShowPhotoPresenter.swift
//  MarsRovers
//
//  Created by Henrique Velloso on 06/03/19.
//  Copyright (c) 2019 Henrique Velloso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowPhotoPresentationLogic
{
  func presentSomething(response: ShowPhoto.Something.Response)
}

class ShowPhotoPresenter: ShowPhotoPresentationLogic
{
  weak var viewController: ShowPhotoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowPhoto.Something.Response)
  {
    let viewModel = ShowPhoto.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
